version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: google-keep-db
    environment:
      MYSQL_DATABASE: google_keep_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: google-keep-api
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/google_keep_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
